{{--
  Trang tra cứu đơn hàng Kim Thành Tín Logistics.
  Route: /tra-cuu-don-hang
  View: frontend.pages.tra-cuu-don-hang
--}}
<!doctype html>
<html lang="vi">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#0b1428">
  <title>Tra cứu vận đơn | Kim Thành Tín Logistics</title>
  <style>
    :root{--navy:#071126;--navy2:#0e1a34;--red:#be2026;--red2:#841419;--gold:#ffd229;--ink:#162137;--muted:#68758b;--line:#e4e9f1;--green:#19a55a;--soft:#f6f8fb}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#edf1f7;color:#fff;font:16px Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}button,input{font:inherit}.hidden{display:none!important}
    .shell{position:relative;overflow:hidden;min-height:76vh;background:radial-gradient(circle at 80% 10%,rgba(255,210,41,.13),transparent 26%),radial-gradient(circle at 8% 90%,rgba(190,32,38,.17),transparent 30%),linear-gradient(145deg,#071126 0%,#0e1930 56%,#080f20 100%)}.shell:before{content:"";position:absolute;inset:0;pointer-events:none;opacity:.25;background-image:linear-gradient(rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px);background-size:52px 52px}.shell:after{content:"";position:absolute;right:-170px;bottom:-260px;width:560px;height:560px;border:1px solid rgba(255,210,41,.13);border-radius:50%;box-shadow:0 0 0 70px rgba(255,210,41,.025),0 0 0 140px rgba(255,210,41,.018)}
    .hero{position:relative;z-index:1;max-width:1180px;min-height:76vh;margin:auto;padding:30px 34px 44px;display:flex;flex-direction:column}.top{display:flex;justify-content:space-between;align-items:center;gap:24px}.brand{display:flex;align-items:center}.brand-logo{display:block;width:190px;height:96px;object-fit:contain;object-position:left center;filter:drop-shadow(0 10px 24px rgba(255,200,26,.14))}.support{display:flex;align-items:center;gap:10px;color:#b8c2d5;font-size:13px}.support:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 0 5px rgba(25,165,90,.12)}.support strong{color:#fff;font-weight:700}
    .hero-content{flex:1;display:flex;flex-direction:column;align-items:flex-start;justify-content:center;gap:22px;padding:26px 0 18px}.badge{display:inline-flex;align-items:center;gap:11px;max-width:100%;padding:10px 17px;border:1px solid rgba(255,77,82,.72);border-radius:999px;background:linear-gradient(100deg,rgba(132,20,25,.88),rgba(190,32,38,.96));color:#ffe254;font-size:14px;font-weight:800;line-height:1.35;box-shadow:0 12px 30px rgba(93,7,12,.2)}.badge i{width:9px;height:9px;min-width:9px;border-radius:50%;background:var(--gold);box-shadow:0 0 13px var(--gold)}
    h1{max-width:100%;font-size:clamp(28px,3.5vw,47px);line-height:1.08;letter-spacing:.018em;margin:0;color:var(--gold);font-weight:900;text-transform:uppercase;text-shadow:0 7px 30px rgba(255,210,41,.16);white-space:nowrap}.intro{max-width:720px;margin:-9px 0 2px;color:#c0cadb;font-size:15px;line-height:1.65}
    .search-area{width:100%;max-width:1040px}.search{display:grid;grid-template-columns:50px 1fr auto;align-items:center;width:100%;background:rgba(255,255,255,.98);border:1px solid rgba(255,255,255,.95);border-radius:18px;padding:9px 10px 9px 20px;box-shadow:0 25px 65px rgba(0,0,0,.35),0 0 0 4px rgba(255,255,255,.07);transition:.2s}.search:focus-within{box-shadow:0 25px 65px rgba(0,0,0,.38),0 0 0 4px rgba(255,210,41,.18)}.search svg{color:var(--red);width:26px}.search input{min-width:0;width:100%;border:0;outline:0;color:var(--ink);font-weight:760;font-size:20px;text-transform:uppercase;padding:17px 9px;background:transparent}.search input::placeholder{color:#8d99ad;text-transform:none;font-weight:590}.search button{display:flex;align-items:center;gap:11px;border:0;border-radius:12px;background:linear-gradient(135deg,#c92329,#a8181d);color:#fff;font-weight:820;font-size:17px;padding:18px 27px;cursor:pointer;box-shadow:0 9px 22px rgba(185,31,35,.25);transition:transform .2s,box-shadow .2s,background .2s}.search button:hover{transform:translateY(-2px);background:linear-gradient(135deg,#d72b31,#b61d22);box-shadow:0 13px 26px rgba(185,31,35,.32)}.search button:disabled{opacity:.68;cursor:wait;transform:none}.button-arrow{color:var(--gold);font-size:21px;line-height:1}.hint{display:flex;align-items:center;gap:7px;margin:13px 4px 0;color:#9ba7bc;font-size:13px}.hint code{color:#f6f8ff;background:rgba(255,255,255,.075);padding:4px 8px;border:1px solid rgba(255,255,255,.07);border-radius:6px}.tagline{display:flex;align-items:center;gap:11px;margin:2px 0 0;color:#fff;font-size:clamp(17px,1.8vw,22px);font-weight:620;letter-spacing:.04em}.tagline:before{content:"";width:34px;height:2px;background:var(--gold)}
    .result-wrap{background:linear-gradient(180deg,#edf1f7,#f7f9fc);color:var(--ink);padding:52px 24px 76px}.result{max-width:1060px;margin:auto;border-radius:22px;box-shadow:0 30px 75px rgba(18,32,57,.13)}.notice{max-width:760px;margin:auto;background:#fff;border:1px solid var(--line);border-radius:20px;padding:38px;text-align:center;box-shadow:0 20px 55px rgba(26,39,67,.09)}.notice h2{margin:0 0 9px;font-size:22px}.notice p{margin:0;color:var(--muted);line-height:1.65}.error-icon{display:grid;place-items:center;margin:0 auto 18px;width:54px;height:54px;border-radius:16px;background:#fff0f0;color:var(--red);font-weight:900;font-size:23px;border:1px solid #ffd7d8}
    .order-head{position:relative;overflow:hidden;display:flex;justify-content:space-between;align-items:center;gap:24px;background:linear-gradient(115deg,#821217 0%,#b71d23 62%,#c92a2f 100%);padding:25px 30px;border-radius:22px 22px 0 0;color:#fff;border-bottom:4px solid var(--gold)}.order-head:after{content:"";position:absolute;right:85px;top:-90px;width:240px;height:240px;border:1px solid rgba(255,255,255,.1);border-radius:50%;box-shadow:0 0 0 34px rgba(255,255,255,.025)}.order-head>div,.close{position:relative;z-index:1}.eyebrow{color:var(--gold);font-weight:800;text-transform:uppercase;letter-spacing:.13em;font-size:11px}.order-code{font-size:27px;font-weight:900;letter-spacing:.025em;margin-top:5px}.close{display:grid;place-items:center;border:1px solid rgba(255,255,255,.12);width:45px;height:45px;border-radius:14px;background:rgba(255,255,255,.1);color:#ffd7d8;font-size:26px;cursor:pointer;transition:.2s}.close:hover{background:rgba(255,255,255,.18);transform:rotate(3deg)}
    .summary{display:grid;grid-template-columns:1fr 1fr;gap:16px;background:#fff;padding:26px 28px 12px}.summary-card{position:relative;overflow:hidden;background:var(--soft);border:1px solid var(--line);border-radius:15px;padding:19px 20px}.summary-card:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--gold)}.summary-card:first-child:before{background:var(--red)}.label{color:#7a879b;font-size:11px;font-weight:850;letter-spacing:.13em;text-transform:uppercase}.status-text{font-size:22px;font-weight:900;color:var(--red);margin-top:8px}.location{font-size:19px;font-weight:850;margin-top:8px}
    .timeline-card{background:#fff;padding:24px 34px 31px;border-radius:0 0 22px 22px}.timeline{position:relative;margin:5px 0 0;padding:0;list-style:none}.timeline:before{content:"";position:absolute;left:14px;top:16px;bottom:25px;width:2px;background:var(--line)}.event{position:relative;min-height:77px;padding:0 0 24px 52px}.event:last-child{min-height:0;padding-bottom:0}.dot{position:absolute;left:3px;top:3px;width:24px;height:24px;border-radius:50%;border:5px solid #fff;background:#fff;box-shadow:0 0 0 2px #c9d3e0}.event.done .dot{background:var(--green);box-shadow:0 0 0 2px var(--green)}.event.active .dot{background:var(--gold);box-shadow:0 0 0 3px var(--red)}.event-time{color:#64738c;font-size:13px;font-weight:800;margin-bottom:4px}.event-title{font-size:19px;font-weight:850;line-height:1.3}.event-detail{margin-top:4px;color:var(--muted);white-space:pre-line;line-height:1.55;font-size:14px}.event.pending .event-title,.event.pending .event-time{color:#a2adbd}.privacy{padding-top:18px;border-top:1px solid #edf0f4;font-size:11px;color:#8792a3;text-align:center;margin:25px 0 0;line-height:1.55}
    @media(max-width:700px){.shell{min-height:auto}.hero{min-height:auto;padding:22px 17px 38px}.top{align-items:flex-start}.brand-logo{width:154px;height:80px}.support{display:none}.hero-content{gap:20px;padding:30px 0 6px}.badge{font-size:12px;padding:9px 13px}h1{font-size:clamp(25px,8.4vw,36px);white-space:normal;line-height:1.12}.intro{font-size:14px;margin:-8px 0 0}.search{grid-template-columns:36px 1fr;padding:8px 9px 8px 15px;border-radius:16px}.search input{font-size:16px;padding:14px 5px}.search button{grid-column:1/-1;justify-content:center;width:100%;padding:14px;margin-top:3px}.hint{display:block;line-height:2}.tagline{font-size:16px}.result-wrap{padding:24px 11px 44px}.order-head{padding:21px 18px}.order-code{font-size:21px}.close{width:41px;height:41px}.summary{grid-template-columns:1fr;gap:10px;padding:18px 15px 8px}.summary-card{padding:16px}.status-text{font-size:20px}.location{font-size:17px}.timeline-card{padding:22px 18px 27px}.event{padding-left:45px;padding-bottom:22px}.event-title{font-size:17px}.notice{padding:30px 20px}}
    @media(min-width:701px) and (max-width:1000px){h1{font-size:clamp(30px,4.5vw,42px)}.hero{padding-left:28px;padding-right:28px}}
  </style>
</head>
<body>
<main class="shell">
  <section class="hero">
    <div class="top"><a class="brand" href="{{ url('/') }}" aria-label="Kim Thành Tín Logistics"><img class="brand-logo" src="{{ asset('frontend/images/logo-ktt.png') }}" alt="Logo Kim Thành Tín Logistics"></a><div class="support">Hỗ trợ tra cứu: <strong>Liên hệ nhân viên phụ trách</strong></div></div>
    <div class="hero-content">
      <div class="badge"><i></i> Uỷ Thác XNK &amp; Vận Chuyển Chính Ngạch Trung – Việt</div>
      <h1>Tra Cứu Hành Trình Đơn Hàng</h1>
      <p class="intro">Theo dõi hành trình hàng hoá xuyên suốt từ kho Trung Quốc đến khi giao tận tay khách hàng.</p>
      <div class="search-area">
        <form class="search" id="searchForm">
          <svg width="29" height="29" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-4-4"></path></svg>
          <input id="orderInput" autocomplete="off" spellcheck="false" aria-label="Mã vận đơn" placeholder="Nhập mã hàng của bạn" maxlength="40">
          <button id="searchButton" type="submit"><span>Tra cứu</span><span class="button-arrow">→</span></button>
        </form>
        <p class="hint">Ví dụ: <code>CN081106-38HN</code> hoặc <code>CN081110-6HN</code></p>
      </div>
      <p class="tagline">“Vận chuyển Thần Tốc Xuyên Biên Giới”</p>
    </div>
  </section>
</main>
<section class="result-wrap hidden" id="resultWrap" aria-live="polite">
  <div class="notice hidden" id="message"></div>
  <article class="result hidden" id="result">
    <header class="order-head"><div><div class="eyebrow">Mã vận đơn</div><div class="order-code" id="resultCode"></div></div><button class="close" id="closeResult" aria-label="Đóng kết quả">×</button></header>
    <div class="summary"><div class="summary-card"><div class="label">Trạng thái hiện tại</div><div class="status-text" id="currentStatus"></div></div><div class="summary-card"><div class="label">Vị trí hiện tại</div><div class="location" id="currentLocation"></div></div></div>
    <div class="timeline-card"><ol class="timeline" id="timeline"></ol><p class="privacy">Thông tin tra cứu chỉ phản ánh dữ liệu vận hành đã được cập nhật. Nếu cần hỗ trợ, vui lòng liên hệ nhân viên phụ trách đơn hàng.</p></div>
  </article>
</section>
<script>
(() => {
  const TRACKING_API='https://hethong.kimthanhtinlogistics.vn/api/tracking';
  const $=s=>document.querySelector(s);
  const clean=v=>String(v??'').trim();
  const escapeHtml=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function metricText(v){const raw=clean(v);if(!raw)return '';const number=Number(raw.replace(/\s/g,'').replace(',','.'));return Number.isFinite(number)?number.toLocaleString('vi-VN',{maximumFractionDigits:3}):raw}
  function parseDate(v){if(v instanceof Date)return v;const s=clean(v);let m=s.match(/^(\d{1,2})[\/.\-](\d{1,2})[\/.\-](\d{2,4})$/);if(!m)return null;const day=+m[1],month=+m[2];let y=+m[3];if(y<100)y+=2000;if(day<1||month<1||month>12)return null;const d=new Date(y,month-1,day);return Number.isNaN(+d)||d.getFullYear()!==y||d.getMonth()!==month-1||d.getDate()!==day?null:d}
  function dateText(v){const d=parseDate(v);return d?d.toLocaleDateString('vi-VN'):(clean(v)||'—')}
  async function loadOrder(code){const response=await fetch(`${TRACKING_API}?code=${encodeURIComponent(code)}`,{headers:{Accept:'application/json'},cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Không thể tải dữ liệu Lark');return data}
  function buildTracking(data){const {entered,weightKg,volumeM3,vehicle,loaded,vehicleStatus,customs,hanoi}=data;const statusKey=clean(vehicleStatus).toLocaleUpperCase('vi-VN').normalize('NFD').replace(/[\u0300-\u036f]/g,'');const isInspection=statusKey.includes('KIEM HOA');const measurements=[weightKg?`Khối lượng: ${metricText(weightKg)} kg`:'',volumeM3?`Thể tích: ${metricText(volumeM3)} m³`:''].filter(Boolean).join('  •  ');const warehouseDetail=['Hàng đã được ghi nhận trên hệ thống kho.',measurements].filter(Boolean).join('\n');const deliveryRows=data.deliveries||[];const delivered=deliveryRows.length>0;const deliveryDate=delivered?deliveryRows[deliveryRows.length-1].date:'';const totalPackages=deliveryRows.reduce((sum,r)=>sum+(Number(String(r.packages||0).replace(',','.'))||0),0);const packageText=totalPackages.toLocaleString('vi-VN');const deliveryDetail=!delivered?'Liên hệ nhân viên phụ trách nếu cần hẹn giao.':deliveryRows.length===1?`1 lần giao, tổng ${packageText} kiện.`:`${deliveryRows.length} lần giao, tổng ${packageText} kiện:\n${deliveryRows.map((r,i)=>`Lần ${i+1}: ngày ${dateText(r.date)} — ${r.packages||0} kiện`).join('\n')}`;
    const steps=[{key:'warehouse',done:!!entered,title:'Đã nhận hàng tại kho Trung Quốc',date:entered,detail:warehouseDetail},{key:'loaded',done:!!(loaded||vehicle),title:loaded||vehicle?'Đã bốc xe':'Chờ bốc xe',date:loaded,detail:vehicle?`Xe: ${vehicle}`:'Đang chờ sắp xếp xe vận chuyển.'},{key:'customs',done:!!customs,current:isInspection&&!customs,title:customs?'Đã thông quan':isInspection?'Đang kiểm hóa':'Chờ thông quan',date:customs,detail:customs?'Xe đã được xác nhận ĐÃ THÔNG QUAN.':isInspection?'Xe đang trong quá trình kiểm hóa tại cửa khẩu.':''},{key:'hanoi',done:!!hanoi,title:hanoi?'Đã về kho Hà Nội':'Chờ về kho Hà Nội',date:hanoi,detail:hanoi?'Hàng đã được hạ tại kho Hà Nội.':''},{key:'delivered',done:delivered,title:delivered?'Đã giao hàng':'Chờ giao hàng',date:deliveryDate,detail:deliveryDetail}];
    let activeIndex=0;steps.forEach((step,index)=>{if(step.done||step.current)activeIndex=index});const current=steps[activeIndex];const location=delivered?'Đã giao tới khách hàng':hanoi?'Kho Hà Nội':customs?'Đang vận chuyển về Hà Nội':isInspection?'Cửa khẩu – đang kiểm hóa':loaded||vehicle?'Trên tuyến Trung Quốc – Việt Nam':'Kho Trung Quốc';return {steps,activeIndex,current,location,vehicle}
  }
  function showMessage(title,text){$('#result').classList.add('hidden');const m=$('#message');m.innerHTML=`<div class="error-icon">!</div><h2>${escapeHtml(title)}</h2><p>${escapeHtml(text)}</p>`;m.classList.remove('hidden');$('#resultWrap').classList.remove('hidden');m.scrollIntoView({behavior:'smooth',block:'center'})}
  function showResult(code,tracking){$('#message').classList.add('hidden');$('#resultCode').textContent=code;$('#currentStatus').textContent=tracking.current.title;$('#currentLocation').textContent=tracking.location;$('#timeline').innerHTML=tracking.steps.map((x,i)=>{const active=i===tracking.activeIndex;return `<li class="event ${x.done?'done':'pending'} ${active?'active':''}"><span class="dot"></span><div class="event-time">${x.date?dateText(x.date):(x.current?'Đang xử lý':x.done?'Đã cập nhật':'Dự kiến')}</div><div class="event-title">${escapeHtml(x.title)}</div><div class="event-detail">${escapeHtml(x.detail)}</div></li>`}).join('');$('#result').classList.remove('hidden');$('#resultWrap').classList.remove('hidden');$('#resultWrap').scrollIntoView({behavior:'smooth',block:'start'})}
  $('#searchForm').addEventListener('submit',async e=>{e.preventDefault();const code=clean($('#orderInput').value);if(!code)return showMessage('Vui lòng nhập mã vận đơn','Ví dụ: CN081106-38HN.');const btn=$('#searchButton');btn.disabled=true;btn.innerHTML='<span>Đang tra cứu…</span>';try{const data=await loadOrder(code);if(!data.found)showMessage('Không tìm thấy mã vận đơn',`Chưa có dữ liệu cho mã ${code}. Vui lòng kiểm tra lại ký tự hoặc liên hệ nhân viên phụ trách.`);else showResult(data.code,buildTracking(data))}catch(err){console.error(err);showMessage('Chưa tải được dữ liệu','Vui lòng kiểm tra kết nối mạng và thử lại sau ít phút.')}finally{btn.disabled=false;btn.innerHTML='<span>Tra cứu</span><span class="button-arrow">→</span>'}});
  $('#closeResult').addEventListener('click',()=>{$('#resultWrap').classList.add('hidden');$('#orderInput').focus()});
  const q=new URLSearchParams(location.search).get('code');if(q){$('#orderInput').value=q;$('#searchForm').requestSubmit()}
})();
</script>
</body>
</html>
